server:
  port: 9001

spring:
  application:
    name: post-micro-service
  datasource:
    password: 1
    url: jdbc:postgresql://localhost:5432/posts
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
